<?php

namespace Pool\LinkmotorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KeywordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeywordRepository extends EntityRepository
{
    /**
     * @param Project $project
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryForKeywordIndex(Project $project)
    {
        $query = $this->getEntityManager()
            ->getRepository('PoolLinkmotorBundle:Keyword')
            ->createQueryBuilder('k')
            ->where('k.project = :project')
            ->setParameter('project', $project->getId());

        return $query;
    }

    /**
     * @return Keyword|null
     */
    public function getNextKeywordToImport()
    {
        $keywords = $this->getEntityManager()
            ->createQuery(
                "SELECT k
                 FROM PoolLinkmotorBundle:Keyword k
                 WHERE k.importInterval > 0 AND (k.lastImportAt IS NULL OR DATE_SUB(:now, k.importInterval, 'DAY') >= k.lastImportAt)
                 ORDER BY k.lastImportAt ASC"
            )
            ->setMaxResults(1)
            ->setParameter('now', new \DateTime())
            ->getResult();

        if ($keywords) {
            return $keywords[0];
        }

        return null;
    }

    /**
     * @return int
     */
    public function getTotalCount()
    {
        return $this->getEntityManager()
            ->getRepository('PoolLinkmotorBundle:Keyword')
            ->createQueryBuilder('k')
            ->select('COUNT(k)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
